### ISSUE TITLE
How to access private registry with self signed certs?

### ISSUE THREAD

**Issue by itheiss** [shipyard/shipyard#603]
Hi!

Is it possible to access a tls enabled private registry with self signed certs? I had no luck at all . And if not is this planed for the future?

Thanks and regards

Ingo

**Comment by ehazlett** [comment]
Are you trying to run containers or manage via the registry management in the UI?

**Comment by itheiss** [comment]
I have added my local registry (v2!) via UI. The registry is tls enabled and I am using selfs signed certs by my own ca.

![ui_registry](https://cloud.githubusercontent.com/assets/2655169/9952643/80d98cd8-5dd8-11e5-9227-696564076b37.jpg)

But when clicking the search button I get only this error:

![ui_registry_error](https://cloud.githubusercontent.com/assets/2655169/9952669/b0ce4618-5dd8-11e5-8c42-45d37959902c.jpg)

This error gets logged by the registry:

```2015/09/18 05:38:20 http: TLS handshake error from 172.17.42.1:45859: remote error: bad certificate ```

**Comment by beyondblog** [comment]
Currently, only registry V1 ) via UI. And does not support the certificate : )

**Comment by tombee** [comment]
I've added some validation to the add registry screen in #608

**Comment by tprobinson** [comment]
Hello,

This may not be very officially supported, but I have been able to get Shipyard to trust a self-signed certificate by overriding its entrypoint.

Here's the relevant section of the `docker-compose.yaml` that I use:
```yaml
  shipyard_controller:
    image: shipyard/shipyard:latest
    container_name: shipyard_controller
    restart: always

    ports:
     - "8080:8080"

    volumes:
     - ./shipyard-entrypoint.sh:/shipyard-entrypoint.sh
     - ./registry.crt:/registry.crt

    entrypoint: ["/shipyard-entrypoint.sh"]
```

The relevant section of `shipyard-entrypoint.sh` ($DOCKER_HOST is generated earlier in the script):
```bash
echo "Configuring SSL trust..."
echo

cp /registry.crt /usr/local/share/ca-certificates/registry.crt
update-ca-certificates

echo "Running Shipyard..."
echo

/bin/controller server -d ${DOCKER_HOST}
```


This causes the Alpine OS image to trust the certificate and allows a local private repository to be added. Note that the file has to end up as a `.crt` or `update-ca-certificates` will ignore it.
