### ISSUE TITLE
"TypeError: Cannot read property 'split' of undefined"  when deploy containers.

### ISSUE THREAD

**Issue by tuxknight** [shipyard/shipyard#723]
Hi everyone,
    I was stucked in loading page of "http://10.1.1.43:8083/#/deploy" which shows "Launching Container" when I tried to **deploy container** .
- Version
  
  ```
  shipyard version 3.0.2 (8e84bed)
  
  swarm version 1.0.1 (744e3a3)
  ```
- configuration
1. a swarm cluster with 4 nodes
2. without docker-proxy
3. setup configuration

```
rethinkdb:
  image: registry.idc/rethinkdb:latest
  restart: always
  ports:
    - 8084:8080
  volumes:
    - ./rethinkdb_data:/data

shipyard:
  image: registry.idc/shipyard:latest
  restart: always
  ports:
    - 8083:8080
  links:
    - rethinkdb:rethinkdb
  command: server --rethinkdb-addr rethinkdb:28015 --rethinkdb-database "shipyard" --docker "tcp://10.1.1.43:3375" --enable-cors
```

```
And I found a bunch of  errors in Chrome console.
```

```
TypeError: Cannot read property 'Names' of null
    at shortestContainerName (containers.controller.js:288)
    at ContainersController.containerName (containers.controller.js:278)
    at angular.js:12474
    at Object.<anonymous> (angular.js:12883)
    at n.$digest (angular.js:14404)
    at n.$apply (angular.js:14675)
    at angular.js:16423
    at e (angular.js:4940)
    at angular.js:5328(anonymous function) @ angular.js:11706(anonymous function) @ angular.js:8619n.$digest @ angular.js:14430n.$apply @ angular.js:14675(anonymous function) @ angular.js:16423e @ angular.js:4940(anonymous function) @ angular.js:5328
angular.js:11706 TypeError: Cannot read property 'Names' of null
    at shortestContainerName (containers.controller.js:288)
    at ContainersController.containerName (containers.controller.js:278)
    at angular.js:12474
    at Object.<anonymous> (angular.js:12883)
    at n.$digest (angular.js:14404)
    at n.$apply (angular.js:14675)
    at l (angular.js:9725)
    at F (angular.js:9915)
    at XMLHttpRequest.C.onload (angular.js:9856)(anonymous function) @ angular.js:11706(anonymous function) @ angular.js:8619n.$digest @ angular.js:14430n.$apply @ angular.js:14675l @ angular.js:9725F @ angular.js:9915C.onload @ angular.js:9856
angular.js:11706 TypeError: Cannot read property 'split' of undefined
    at new ContainerDeployController (http://10.1.1.43:8083/app/containers/deploy.controller.js:18:38)
    at e (http://10.1.1.43:8083/bower_components/angular/angular.min.js:36:315)
    at Object.instantiate (http://10.1.1.43:8083/bower_components/angular/angular.min.js:36:432)
    at http://10.1.1.43:8083/bower_components/angular/angular.min.js:76:5
    at http://10.1.1.43:8083/bower_components/ui-router/release/angular-ui-router.min.js:7:23333
    at Z (http://10.1.1.43:8083/bower_components/angular/angular.min.js:70:149)
    at I (http://10.1.1.43:8083/bower_components/angular/angular.min.js:59:255)
    at g (http://10.1.1.43:8083/bower_components/angular/angular.min.js:51:335)
    at http://10.1.1.43:8083/bower_components/angular/angular.min.js:50:444
    at k (http://10.1.1.43:8083/bower_components/ui-router/release/angular-ui-router.min.js:7:22678) <div id="content" ui-view="" class="ng-scope">(anonymous function) @ angular.js:11706(anonymous function) @ angular.js:8619Z @ angular.js:8283I @ angular.js:7791g @ angular.js:7140(anonymous function) @ angular.js:7019k @ angular-ui-router.min.js:7(anonymous function) @ angular-ui-router.min.js:7n.$broadcast @ angular.js:14889y.transition.M.then.y.transition.y.transition @ angular-ui-router.min.js:7(anonymous function) @ angular.js:13318n.$eval @ angular.js:14570n.$digest @ angular.js:14386n.$apply @ angular.js:14675l @ angular.js:9725F @ angular.js:9915C.onload @ angular.js:9856
```
