### ISSUE TITLE
Internal error on some endpoints (3.0.2)

### ISSUE THREAD

**Issue by mathroc** [shipyard/shipyard#751]
Hi,

I've install shipyard but some functionalities are not working. I can list nodes ( and I see the one node in my swarm) but when trying to list images or containers (`GET /images/json?all=1` & `GET /containers/json?all=1`), the API returns :

``` http-response
HTTP/1.1 500 Internal Server Error
Content-Length: 21
Content-Type: text/plain; charset=utf-8

Internal Server Error
```

I've tried to start shipyard with the `--debug` option but it only shows this in the log:

``` log
app_1 | time="2016-02-14T19:00:17Z" level=debug msg="GET: /containers/json?all=1"
app_1 | time="2016-02-14T19:01:06Z" level=debug msg="GET: /images/json?all=1"
```

note: listing images & container using `docker -H <swarm> …` is working

I don't know if this is a bug a in shipyard or a problem with my setup. what can I try to get more information ?

**Comment by borzamircea** [comment]
+1

**Comment by eitanshp** [comment]
+1

**Comment by 0x4139** [comment]
any info regarding this?
```
{"data":"Internal Server Error","status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/containers/json?all=1","headers":{"Accept":"application/json, text/plain, */*","X-Access-Token":"admin:$2a$10$hdPjh3xrVkHl.a6NfdwM1u2wclAwzBjdZnk74QfW70XtMSXi2QO7O"}},"statusText":"Internal Server Error"}
```

**Comment by ehazlett** [comment]
What version of docker and Swarm?

**Comment by twang2218** [comment]
same here. I created a swarm cluster: 1 kvstore, 1 master, 3 nodes. And try the following `docker-compose.yml` to start the shipyard on the master node:

```yml
version: '2'
services:
    datastore:
        image: rethinkdb
        restart: always
        networks:
            shipyard:
                aliases:
                    - rethinkdb
    controller:
        image: shipyard/shipyard:latest
        restart: always
        networks:
            - shipyard
        ports:
            - "8080:8080"
        command: --debug server --enable-cors -d tcp://192.168.99.101:3376
        depends_on:
            - datastore
networks:
    shipyard:
```

The shipyard started successfully, however, I cannot see any information on the page, as the "500 Internal Server Error" error:

```
Error...
{"data":"Internal Server Error","status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/containers/json?all=1","headers":{"Accept":"application/json, text/plain, */*","X-Access-Token":"admin:$2a$10$MHs7VgMETebuiiZgvsRnaOzgbgZOqWi7Uv.lT7VxoGg5oW0uk789m"}},"statusText":"Internal Server Error"}
```

And the shipyard controller log shows nothing about the error, even I started it with `--debug`:

```
controller_1  | time="2016-06-30T18:28:57Z" level=debug msg="GET: /containers/json?all=1" 
controller_1  | time="2016-06-30T18:29:13Z" level=debug msg="GET: /containers/json?all=1" 
controller_1  | time="2016-06-30T18:29:39Z" level=debug msg="GET: /containers/json?all=1" 
```
