### ISSUE TITLE
Running shipyard with Compose

### ISSUE THREAD

**Issue by kayone** [shipyard/shipyard#926]
I'm trying to run shipyard using compose and images available on docker hub.

```
rethinkdb:
    image: rethinkdb
    ports:
        - "8080"
        - "28015"
        - "29015"
proxy:
    image: ehazlett/docker-proxy:latest
    command: -i
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
        - "2375"

swarm:
    image: swarm:latest
    command: m --host tcp://0.0.0.0:2375 proxy:2375
    links:
        - "proxy:proxy"
    ports:
        - "2375"

controller:
    image: shipyard/shipyard
    command: server
    links:
        - rethinkdb
        - swarm
    ports:
        - "8080:8080"
```

I've got this far, and the controller seems to come up, however I get this error on the dashboard,

```
{"data":"Bad Gateway","status":502,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/containers/json?all=1","headers":{"Accept":"application/json, text/plain, */*","X-Access-Token":"admin:$2a$10$NQ6..gO/wB6tvq4Sv0fmz.V/eJmQsa42vA1XVhG6.njSPXZMBLRWm"}},"statusText":"Bad Gateway"}
```

I'm pretty sure it has something to do with my compose file and some pieces missing/not connected correctly,
